apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 2 # Adjust the number of replicas as needed for scalability
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-container
          image: shaheer12/apigateway:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"  # Specify the desired memory request
              cpu: "100m"    
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /api/status
              port: 3000
          livenessProbe:
            httpGet:
              path: /api/status
              port: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: quotes-api-config
data:
  QUOTES_API: "http://quotes:5000"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: api-resource-quota
spec:
  hard:
    cpu: "2"
    memory: 3Gi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-deployment
  minReplicas: 2 # Minimum number of replicas
  maxReplicas: 5 # Maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # Adjust the target CPU utilization percentage
