apiVersion: v1
kind: Service
metadata:
  name: quotes-service
spec:
  selector:
    app: quotes
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotes-deployment
spec:
  replicas: 2 # Adjust the number of replicas as needed for scalability
  selector:
    matchLabels:
      app: quotes
  template:
    metadata:
      labels:
        app: quotes
    spec:
      containers:
        - name: quotes-container
          image: shaheer12/quoteservice:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"  # Specify the desired memory request
              cpu: "100m"  
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /api/quote
              port: 5000
          livenessProbe:
            httpGet:
              path: /api/quote
              port: 5000
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quotes-resource-quota
spec:
  hard:
    cpu: "1"
    memory: 3Gi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: quotes-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: quotes-deployment
  minReplicas: 2 # Minimum number of replicas
  maxReplicas: 5 # Maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 # Adjust the target CPU utilization percentage
